### ISSUE TITLE
incompatible graph api with fbrest

### ISSUE THREAD

**Issue by kirill578** [marsbits/restfbmessenger#6]
the response from facebook graph api when trying to get user by his id contains:
`profile_pic` which is a String url
however the mapping of the fbrest library in the type.User object
has no such value. thus when you try to get the profile photo you get null

**Comment by marceloverdijk** [comment]
Hi @kirill578,  Sorry for not responding earlier. This one slipped my mind apparently :-(

I've upgraded the restfbmessenger lib to the latest restfb `1.36.0` release. The new restfbmessenger `1.2.0` is available in Maven Central.
Can you check if the problem still exists in that version. Otherwise we have to raise an issue at https://github.com/restfb/restfb as this library uses the restfb types.

Please let me know.
